add gh perms

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,44 +1,51 @@
-name: ci
+name: CI & Deploy
 
-on: push
+on:
+  push:
+    branches: [master]
+
+permissions:
+  contents: read
+  pages: write
+  id-token: write
 
 jobs:
   ci:
-    runs-on: ${{ matrix.os }}
-
-    strategy:
-      matrix:
-        os: [ubuntu-latest]
-        node: [22]
-
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout
-        uses: actions/checkout@v6
+        uses: actions/checkout@v4
 
       - name: Install pnpm
         uses: pnpm/action-setup@v4
+        with:
+          run_install: false
 
       - name: Install node
-        uses: actions/setup-node@v6
+        uses: actions/setup-node@v4
         with:
-          node-version: ${{ matrix.node }}
+          node-version: 22
           cache: pnpm
 
       - name: Install dependencies
         run: pnpm install
 
       # - name: Lint
-      #   run: pnpm run lint
+      # run: pnpm run lint || echo "Lint failed but continuing" # Voorkomt stop bij kleine waarschuwingen
 
       # - name: Typecheck
-      #   run: pnpm run typecheck
+      # run: pnpm run typecheck
 
-      - name: Build
-        run: pnpm build
+      - name: Generate Static Site
+        run: pnpm run generate
+
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v3
+        with:
+          path: .output/public
 
   deploy:
     needs: ci
-    if: github.ref == 'refs/heads/master'
     runs-on: ubuntu-latest
     environment:
       name: github-pages
